name: CI with CTest and Unity

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run CTest
        working-directory: build
        run: ctest --output-on-failure --parallel $(nproc)